config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    registrations: 'registrations', 
    omniauth_callbacks: 'users/omniauth_callbacks' } do
    get '/users/sign_out' => 'devise/sessions#destroy' 
  end

  namespace :api, defaults: { format: :json } do
    scope module: :v1 do
      resources :devs, only: [:index]
      resources :jobs, only: [:index]
    end
  end

  get 'home/index'
  root 'home#index'

  post '/create' => 'home#create', :as => :create
  get '/home/index/:slack_id', to: 'home#index'
  get '/success' => 'home#success', :as => :success  
  get '/careers/' => 'careers#index'
  get '/careers/all_devs' => 'careers#all_devs'
  get '/careers/all_jobs' => 'careers#all_jobs'
  get '/careers/manage' => 'careers#manage'
  resources :jobs

end

app/models/job.rb
class Job < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  belongs_to :user

  scope :remote_options, -> (remote_options) { where remote_options: remote_options }
  scope :title_like, -> (title) { where("title like ?", "%#{title}%")}
  scope :description_like, -> (description) { where("description like ?", "%#{description}%")}

  validates :url, :url => true

  def slug_candidates
    [
      :title,
      [:company, :title]
    ]
  end
end

app/controllers/api/v1/jobs_controller.rb
class Api::V1::JobsController < ApiController
  respond_to :json

  def index
    jobs = Job.all.order('post_date DESC')
    jobs = jobs.remote_options(params[:remote_options]) if params[:remote_options].present?
    jobs = jobs.title_like(params[:title_like]) if params[:title_like].present?
    jobs = jobs.description_like(params[:description_like]) if params[:description_like].present?
    respond_with jobs
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, except: :show

  def index
    @jobs = Job.where(user: current_user).order('post_date DESC')
  end

  def new
      @job = Job.new
  end

  def create
    return unless params['job']

    params['job']['user_id'] = current_user.id
    params['job']['post_date'] = DateTime.now

    @job = Job.new(job_params)

    if @job.save!
      redirect_to @job
    else
      render 'new'
    end
  end

  def edit    
    @job = Job.friendly.find(params[:id])
  end

  def update
    @job = Job.friendly.find(params[:id])
    @job.post_date = DateTime.now

    if @job.update_attributes(job_params)
      redirect_to @job
    else
      flash[:notice] = @job.errors.messages.to_a.join(' ')
      render 'edit'
    end
  end

  def show
    @job = Job.friendly.find(params[:id])
  end

  def destroy
    @job = Job.friendly.find(params[:id])
    
    if current_user.id == @job.user.id then 
      @job.destroy
      redirect_to :jobs
    end
  end

  def job_params 
    params.require(:job).permit(:user_id, :title, :description, :company, :url, :remote_options, :post_date)
  end 

end

app/views/jobs/edit.html.haml
.row
  .col-md-7.col-md-offset-2
    %h2
      Edit Opportunity
    = form_for(@job, html: { class: 'form-horizontal'}) do |f|
      .form-group
        %label.col-sm-4.control-label{for: 'title'} Title/Position:
        .col-sm-7
          = f.text_field :title, autofocus: true, class: 'form-control', required: 'required'    
      .form-group
        %label.col-sm-4.control-label{for: 'company'} Company:
        .col-sm-7
          = f.text_field :company, autofocus: true, class: 'form-control', required: 'required'   
      .form-group
        %label.col-sm-4.control-label{for: 'url'}URL:
        .col-sm-7
          = f.text_field :url, autofocus: true, class: 'form-control', required: 'required', plackeholder: 'http://'      
      .form-group
        %label.col-sm-4.control-label{for: 'remote_options'} Remote Options:
        .col-sm-7
          = f.select(:remote_options, options_for_select(["No Remote", "Some Remote", "Mostly Remote", "Remote Only"], selected: f.object.remote_options),{}, {class: 'form-control'})          
      .form-group
        %label.col-sm-4.control-label{for: 'description'}Description:
        .col-sm-7
          = f.text_field :description, autofocus: true, class: 'form-control'   
      .form-group
        %label.col-sm-4.control-label Author:
        %label.col-sm-7.control-label{style: 'text-align: left;'}
          = current_user.fullname
      .form-group
        %label.col-sm-4.control-label Expires:
        %label.col-sm-7.control-label{style: 'text-align: left;'}
          = DateTime.now+30
      .form-group
        .col-sm-offset-6
          = f.submit "Save", class: 'btn btn-primary'      

app/views/jobs/index.html.haml
.row  
  .col-md-12
    .page_top{style: 'overflow: auto;'}
      = link_to 'Add New Job', :new_job, class: 'btn btn-success pull-right'
    %hr
    %table.stripe
      %thead
        %th
          Title
        %th
          Company  
        %th
          Url
        %th
          Post Date
        %th
      %tbody
        - @jobs.each do |job|
          %tr
            %td 
              = link_to job.title, job 
            %td 
              = job.company
            %td
              = link_to job.url, job.url
            %td
              = job.post_date.to_s(:short)
            %td{style: 'width:150px;'}
              #{link_to "Edit", edit_job_path(job), class: 'btn btn-info pull-left'} 
              #{button_to "Delete", job_path(job.id), data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-warning pull-right'} 
:javascript
  $(document).ready(function() {
      $('table').DataTable();
  } );

app/views/jobs/new.html.haml
.row
  .col-md-7.col-md-offset-2
    %h2
      Add Opportunity
    = form_for(@job, html: { class: 'form-horizontal'}) do |f|
      .form-group
        %label.col-sm-4.control-label{for: 'title'} Title/Position:
        .col-sm-7
          = f.text_field :title, autofocus: true, class: 'form-control', required: 'required'    
      .form-group
        %label.col-sm-4.control-label{for: 'company'} Company:
        .col-sm-7
          = f.text_field :company, autofocus: true, class: 'form-control', required: 'required'   
      .form-group
        %label.col-sm-4.control-label{for: 'url'}URL:
        .col-sm-7
          = f.text_field :url, autofocus: true, class: 'form-control', required: 'required', placeholder: 'http://'    
      .form-group
        %label.col-sm-4.control-label{for: 'remote_options'} Remote Options:
        .col-sm-7
          = f.select(:remote_options, options_for_select(["No Remote", "Some Remote", "Mostly Remote", "Remote Only"], selected: f.object.remote_options),{}, {class: 'form-control'})          
      .form-group
        %label.col-sm-4.control-label{for: 'description'}Description:
        .col-sm-7
          = f.text_field :description, autofocus: true, class: 'form-control'   
      .form-group
        %label.col-sm-4.control-label Author:
        %label.col-sm-7.control-label{style: 'text-align: left;'}
          = current_user.fullname
      .form-group
        %label.col-sm-4.control-label Expires:
        %label.col-sm-7.control-label{style: 'text-align: left;'}
          = DateTime.now+30
      .form-group
        .col-sm-offset-6
          = f.submit "Save", class: 'btn btn-primary'      

app/views/jobs/show.html.haml
.row
  .col-md-7.col-md-offset-2
    .page_top{style: 'overflow: auto;'}
      = link_to 'Manage Jobs', :jobs, class: 'btn btn-success pull-right' if current_user
    %hr  
    %h2
      Opportunity Details
    .row
      %label.col-sm-4.control-label{for: 'title'} Title/Position:
      %label.col-sm-7.control-label{style: 'text-align: left;'}= @job.title  
    .row
      %label.col-sm-4.control-label{for: 'company'} Company:
      %label.col-sm-7.control-label{style: 'text-align: left;'}= @job.company
    .row
      %label.col-sm-4.control-label{for: 'url'}URL:
      %label.col-sm-7.control-label{style: 'text-align: left;'}
        = link_to @job.url, @job.url
    .row
      %label.col-sm-4.control-label{for: 'remote_options'} Remote Options:
      %label.col-sm-7.control-label{style: 'text-align: left;'}= @job.remote_options
    .row
      %label.col-sm-4.control-label{for: 'description'} Description:
      %label.col-sm-7.control-label{style: 'text-align: left;'}= @job.description
    .row
      %label.col-sm-4.control-label Share To:
      %label.col-sm-7.control-label.share-links{style: 'text-align: left; font-size:20px;'}
        = link_to CareerHelper.get_facebook_url(@job), target: :blank do
          %i.fa.fa-facebook-official
        = link_to CareerHelper.get_twitter_url(@job), target: :blank do
          %i.fa.fa-twitter        
    .row
      %hr  
    .row
      %label.col-sm-4.control-label Author:
      %label.col-sm-7.control-label{style: 'text-align: left;'}= @job.user.fullname
    .row
      %label.col-sm-4.control-label Posted:
      %label.col-sm-7.control-label{style: 'text-align: left;'}= @job.post_date
    .row
      %label.col-sm-4.control-label Expires:
      %label.col-sm-7.control-label{style: 'text-align: left;'}= @job.post_date + 30.days